-- AuthHexagonalApi - Schema PostgreSQL (Identity + colunas customizadas)
-- Objetivo: permitir criar o banco via pgAdmin4 sem rodar migrations do EF.
--
-- Como usar (pgAdmin4):
-- 1) Crie um banco (ex.: AuthHexagonalDb)
-- 2) Abra o Query Tool conectado nesse banco
-- 3) Execute este arquivo (schema.sql)
-- 4) Depois execute database/seed.sql (opcional)

BEGIN;

-- Tabela de histórico de migrations (opcional, mas útil)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
  "MigrationId" character varying(150) NOT NULL,
  "ProductVersion" character varying(32) NOT NULL,
  CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Roles
CREATE TABLE IF NOT EXISTS "AspNetRoles" (
  "Id" uuid NOT NULL,
  "Name" character varying(256) NULL,
  "NormalizedName" character varying(256) NULL,
  "ConcurrencyStamp" text NULL,
  CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

-- Users (ApplicationUser)
CREATE TABLE IF NOT EXISTS "AspNetUsers" (
  "Id" uuid NOT NULL,
  "RefreshTokenHash" character varying(256) NULL,
  "RefreshTokenExpiryTime" timestamp with time zone NULL,
  "CreatedAt" timestamp with time zone NOT NULL,

  "UserName" character varying(256) NULL,
  "NormalizedUserName" character varying(256) NULL,
  "Email" character varying(256) NULL,
  "NormalizedEmail" character varying(256) NULL,
  "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
  "PasswordHash" text NULL,
  "SecurityStamp" text NULL,
  "ConcurrencyStamp" text NULL,
  "PhoneNumber" text NULL,
  "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
  "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
  "LockoutEnd" timestamp with time zone NULL,
  "LockoutEnabled" boolean NOT NULL DEFAULT FALSE,
  "AccessFailedCount" integer NOT NULL DEFAULT 0,

  CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

-- Role claims
CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "RoleId" uuid NOT NULL,
  "ClaimType" text NULL,
  "ClaimValue" text NULL,
  CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
    REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

-- User claims
CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "UserId" uuid NOT NULL,
  "ClaimType" text NULL,
  "ClaimValue" text NULL,
  CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- User logins
CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
  "LoginProvider" text NOT NULL,
  "ProviderKey" text NOT NULL,
  "ProviderDisplayName" text NULL,
  "UserId" uuid NOT NULL,
  CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
  CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- User roles
CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
  "UserId" uuid NOT NULL,
  "RoleId" uuid NOT NULL,
  CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
  CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
    REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- User tokens
CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
  "UserId" uuid NOT NULL,
  "LoginProvider" text NOT NULL,
  "Name" text NOT NULL,
  "Value" text NULL,
  CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
  CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- Indexes (compatíveis com Identity)
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

COMMIT;

